# Docker

# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master
  
resources:
  - repo: self
  
variables:
    tag: 'latest'
    imageName: 'ikifar/docker-hoobs'
  
stages:
  - stage: Build
    displayName: Build image
    jobs:  
    - job: Build
      displayName: Build
      pool:
        name: 'Default'
        vmImage: 'ubuntu-latest'
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker Hub ikifar'
            repository: 'ikifar/docker-hoobs'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(tag)'